/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquisitionRouteImport } from './routes/acquisition'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CustodyRouteImport } from './routes/custody'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MulticamRouteImport } from './routes/multicam'
import { Route as OemRouteImport } from './routes/oem'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SopRouteImport } from './routes/sop'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VideoRouteImport } from './routes/video'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'
import { Route as CasesNewRouteImport } from './routes/cases/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionRoute = AcquisitionRouteImport.update({
  id: '/acquisition',
  path: '/acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustodyRoute = CustodyRouteImport.update({
  id: '/custody',
  path: '/custody',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MulticamRoute = MulticamRouteImport.update({
  id: '/multicam',
  path: '/multicam',
  getParentRoute: () => rootRouteImport,
} as any)
const OemRoute = OemRouteImport.update({
  id: '/oem',
  path: '/oem',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/ai': typeof AiRoute
  '/audit': typeof AuditRoute
  '/custody': typeof CustodyRoute
  '/devices': typeof DevicesRoute
  '/evidence': typeof EvidenceRoute
  '/files': typeof FilesRoute
  '/findings': typeof FindingsRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/multicam': typeof MulticamRoute
  '/oem': typeof OemRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sop': typeof SopRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/video': typeof VideoRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/ai': typeof AiRoute
  '/audit': typeof AuditRoute
  '/custody': typeof CustodyRoute
  '/devices': typeof DevicesRoute
  '/evidence': typeof EvidenceRoute
  '/files': typeof FilesRoute
  '/findings': typeof FindingsRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/multicam': typeof MulticamRoute
  '/oem': typeof OemRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sop': typeof SopRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/video': typeof VideoRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisition': typeof AcquisitionRoute
  '/ai': typeof AiRoute
  '/audit': typeof AuditRoute
  '/custody': typeof CustodyRoute
  '/devices': typeof DevicesRoute
  '/evidence': typeof EvidenceRoute
  '/files': typeof FilesRoute
  '/findings': typeof FindingsRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/multicam': typeof MulticamRoute
  '/oem': typeof OemRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sop': typeof SopRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/video': typeof VideoRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisition'
    | '/ai'
    | '/audit'
    | '/custody'
    | '/devices'
    | '/evidence'
    | '/files'
    | '/findings'
    | '/integrity'
    | '/login'
    | '/multicam'
    | '/oem'
    | '/recovery'
    | '/reports'
    | '/settings'
    | '/sop'
    | '/timeline'
    | '/users'
    | '/video'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisition'
    | '/ai'
    | '/audit'
    | '/custody'
    | '/devices'
    | '/evidence'
    | '/files'
    | '/findings'
    | '/integrity'
    | '/login'
    | '/multicam'
    | '/oem'
    | '/recovery'
    | '/reports'
    | '/settings'
    | '/sop'
    | '/timeline'
    | '/users'
    | '/video'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/acquisition'
    | '/ai'
    | '/audit'
    | '/custody'
    | '/devices'
    | '/evidence'
    | '/files'
    | '/findings'
    | '/integrity'
    | '/login'
    | '/multicam'
    | '/oem'
    | '/recovery'
    | '/reports'
    | '/settings'
    | '/sop'
    | '/timeline'
    | '/users'
    | '/video'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionRoute: typeof AcquisitionRoute
  AiRoute: typeof AiRoute
  AuditRoute: typeof AuditRoute
  CustodyRoute: typeof CustodyRoute
  DevicesRoute: typeof DevicesRoute
  EvidenceRoute: typeof EvidenceRoute
  FilesRoute: typeof FilesRoute
  FindingsRoute: typeof FindingsRoute
  IntegrityRoute: typeof IntegrityRoute
  LoginRoute: typeof LoginRoute
  MulticamRoute: typeof MulticamRoute
  OemRoute: typeof OemRoute
  RecoveryRoute: typeof RecoveryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SopRoute: typeof SopRoute
  TimelineRoute: typeof TimelineRoute
  UsersRoute: typeof UsersRoute
  VideoRoute: typeof VideoRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesNewRoute: typeof CasesNewRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisition': {
      id: '/acquisition'
      path: '/acquisition'
      fullPath: '/acquisition'
      preLoaderRoute: typeof AcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custody': {
      id: '/custody'
      path: '/custody'
      fullPath: '/custody'
      preLoaderRoute: typeof CustodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multicam': {
      id: '/multicam'
      path: '/multicam'
      fullPath: '/multicam'
      preLoaderRoute: typeof MulticamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem': {
      id: '/oem'
      path: '/oem'
      fullPath: '/oem'
      preLoaderRoute: typeof OemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionRoute: AcquisitionRoute,
  AiRoute: AiRoute,
  AuditRoute: AuditRoute,
  CustodyRoute: CustodyRoute,
  DevicesRoute: DevicesRoute,
  EvidenceRoute: EvidenceRoute,
  FilesRoute: FilesRoute,
  FindingsRoute: FindingsRoute,
  IntegrityRoute: IntegrityRoute,
  LoginRoute: LoginRoute,
  MulticamRoute: MulticamRoute,
  OemRoute: OemRoute,
  RecoveryRoute: RecoveryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SopRoute: SopRoute,
  TimelineRoute: TimelineRoute,
  UsersRoute: UsersRoute,
  VideoRoute: VideoRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesNewRoute: CasesNewRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
